name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Build Docker Image
      run: docker build -t myapp:latest .

    - name: Push Image (optional)
      run: echo "Push to DockerHub or ECR"

    - name: Deploy to Kubernetes
      run: kubectl apply -f k8s/



      - name: Install Minikube
  run: |
    curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
    sudo install minikube-linux-amd64 /usr/local/bin/minikube

- name: Start Minikube
  run: minikube start --driver=docker --force

- name: Deploy to Kubernetes
  run: kubectl apply -f k8s/
